services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ClientApp/API/WebAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - CleanArchitecture.database 
  CleanArchitecture.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - .\db:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA
    container_name: CleanArchitecture.database
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=P@ssw0rd@123"
    restart: always
    ports:
      - "1433:1433"
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd@123 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s 
  CleanArchitecture.cache:
     image: redis:latest
     restart: always
     ports:
       - 6380:6379

